### ISSUE TITLE
Unable to get better errors to work with scorched

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#31]
I have been trying to implement the 'better_errors' gem as it is the alternative to web console that should work on any rack application

At the moment when implemented I can get the backtrace of the error but not the code and console. If looking at the screenshot on the [README](https://github.com/charliesome/better_errors) for better errors I am just getting the left half of the screen. I think the problem is with the second step to load the code. the JS console on the error page I am getting has the following

> Failed to load resource: the server responded with a status of 500 (Internal Server Error) *http://localhost:9292/__better_errors/8052340bdb489f27/variables*

I have tried getting this to work in an isolated application so can just copy the whole config.ru here

```rb
# setup as development enviroment unless otherwise specified
RACK_ENV = ENV['RACK_ENV'] ||= 'development' unless defined?(RACK_ENV)

# Set Application Root
APP_ROOT = File.expand_path('..', __FILE__) unless defined?(APP_ROOT)

# Load our dependencies
require 'rubygems' unless defined?(Gem)

# Sets up all of load paths that are searched when requiring code
require 'bundler/setup'

# requires all gems for the current runtime enviroment
Bundler.require(:default, RACK_ENV)

# require the lib directory
Dir[APP_ROOT + '/lib/**/*.rb'].each {|file| require file }

class App < Scorched::Controller
  middleware << proc do
    use Rack::Session::Cookie, secret: 'blah'
    use BetterErrors::Middleware

    BetterErrors.application_root = APP_ROOT
    use Rack::Csrf, :raise => true
  end
  
end

class HomeController < App
  get '/' do
    config[:show_exceptions]
  end

  get '/bad_route' do
    1/0
  end
end

App.controller '/', HomeController
run App
```

My lib directory is currently empty. I was wondering if csrf is the problem. but I have tried ommiting one or other middlewares as well as reordering.

Finally here is my gemfile

```rb
source 'https://rubygems.org'

ruby '2.2.0'

gem 'thin'
gem 'shotgun'
gem 'scorched'
gem 'rack_csrf', :require => 'rack/csrf'
gem 'awesome_print'

group :development do
  gem "better_errors"
  gem "binding_of_caller"
end

```

**Comment by Wardrop** [comment]
Not sure, but I can confirm better errors has the same issue with even the simplest of Rack applications, even without Scorched.

```ruby
require 'better_errors'

use BetterErrors::Middleware

run proc { |env| raise "something" }
```

**Comment by CrowdHailer** [comment]
So experimenting with that I noticed that `binding_of_caller` is a required dependency to get that second half working. so the following config file does work

```rb
require 'better_errors'
require 'binding_of_caller'

use BetterErrors::Middleware

run proc { |env| raise "something" }
```

**Comment by CrowdHailer** [comment]
This might be a rack question but should this work?

```rb
require 'scorched'
require 'better_errors'
require 'binding_of_caller'

use BetterErrors::Middleware

run (Class.new(Scorched::Controller) do
  get '/' do
    raise 'something'
  end
end)
```

Because I think that it perhaps should. maybe middlewares are inherited through scorched controllers but not from those declared in config.ru

**Comment by Wardrop** [comment]
Correct. You can load middleware outside of Scorched and it'll work as intended.

**Comment by CrowdHailer** [comment]
Sorry if it wasnt clear but the example before of loading middleware outside the scorched controller (last example) does not work but out side the simple block does

**Comment by Wardrop** [comment]
You need to disable `ShowExceptions` which Scorched has enabled by default in development mode. If you don't disable it, it will rescue the exceptions before `BetterErrors`. 

```ruby
require File.expand_path('../../lib/scorched.rb', __FILE__)
require 'better_errors'
require 'binding_of_caller'

use BetterErrors::Middleware

class App < Scorched::Controller
  config[:show_exceptions] = false
  get '/' do
    raise 'something'
  end
end

run App
```

Also, avoid using proc's in the context of Rack::Builder as you can get name collisions and other potential weirdness due to the proc's binding.

**Comment by CrowdHailer** [comment]
Still only the left half of better errors working. No repl

**Comment by Wardrop** [comment]
Didn't we determine the lack of repl was an issue with BetterErrors? In my test the results were the same regardless of whether Scorched was being used or not. Try it with just a basic rack application; the result will probably be the same.

**Comment by RobinDaugherty** [comment]
Unable to reproduce this with the current release of better_errors (2.3.0). It also displays errors in the right pane when there is an error instead of leaving it blank.

There is a known issue with Shotgun, because better_errors relies on storing exception information between requests, and shotgun causes all dependencies to be reloaded for each request. However, I was able to use better_errors (including the right pane) with scorched 0.27 using the Gemfile and code above, even with shotgun (which makes me think shotgun isn't working in scorched).

**Comment by Wardrop** [comment]
I've never had an issue with shotgun working with Scorched; I use it all the time. How does `better_errors` store information between requests? Perhaps it's using files on the server side, or cookies? Both of those methods would of course work between requests under Shotgun.
