### ISSUE TITLE
helpers to the Root url of the controller

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#34]
I will start this with my example config.ru

```rb
require 'scorched'

class SubController < Scorched::Controller
  get '/' do
    url # Would expect this to show http://localhost:9292/root
  end

  get '/branch' do
    absolute # Similar would expect this to show /root
  end

  # The reason for this is to make methods for url that work regardless of where the controller is used
  def branch_path
    absolute('/branch')
    # in reality required to know how it is mounted as correct method would need to be
    # absolute('root/branch')
  end
end

class App < Scorched::Controller
  controller '/root', SubController
end

run App
```

This was possibly my misunderstanding when reading the docs. So have been considering each Scorched controller as a nice way to build and compose rack applications. Therefore I would expect the subcontroller to be mounted to app and there be a way to get url helpers within a controller. When reading the docs I thought i had found what I was after.

> absolute - Returns the absolute URL of the web application root, with the optional argument joined to the end. For example, if you're application was mounted under example.com/myapp/: absolute '/about' #=> /myapp/about 

Is there away to get a application url just from specifying the controller extension
```rb
# Within subcontroller
relative_url('branch')
# => /root/branch
```

I imagine there might be a use for both but it comes up alot that I have the desire to redirect to the show path after creating a resource so i would use redirect `relative_url("#{resource.id}")` and would like that to work when the controller is mounted within an admin controller within an app controller or just mounted on its own for testing purposes.

**Comment by Wardrop** [comment]
Perhaps what you're after are simply relative paths. Like in your last example `redirect relative_url("#{resource.id}")` you could simply replace that with `redirect ".\#{resource.id}"`. As long as you're using the  `:redirect` option for `config[:strip_trailing_slash]` (which is the default), relative paths work reliably. 

If you do wish to use a particular pattern in your application that involves building a path based on the controller or something like that, you could build one yourself rather trivially using the data available in the `request` object, which is an instance of `Scorched::Request` (https://github.com/Wardrop/Scorched/blob/master/lib/scorched/request.rb). More specifically, the `breadcrumb` method contains the complete list of Scorched controllers that the request has routed through.

I've taken the liberty in creating such a method for you. Below is your example but with a `relative` method implemented. I would still encourage you to use proper relative paths though wherever possible, as I can't think of any scenarios where you would actually NEED this `relative` method.

```ruby
require 'scorched'

class SubController < Scorched::Controller
  get '/' do
    url # Would expect this to show http://localhost:9292/root
  end

  controller '/sub' do
    get '/branch' do
      relative('other_branch')
    end
  end

  # Finds the most recent match that has a Scorched::Controller as it's target, and adds the given `path` to the matched path up to that point.
  def relative(path)
    last_index = request.breadcrumb.rindex { |x| Scorched::Controller > x.mapping[:target] if x.mapping[:target].is_a? Class }
    base = File.join *request.breadcrumb[0..last_index].map { |x| x.path }
    base = absolute(base)
    File.join(base, path)
  end
end

class App < Scorched::Controller
  controller '/root', SubController
end

map "/app" do
  run App
end
```
