### ISSUE TITLE
Adding caught exceptions to env hash

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#35]
Does Scorched keep track of thrown errors anywhere? I would expect them to be in `env['rack.exception'`

If not could this feature be added?

I currently have this hack in my base application to make it happen

```rb
error do
    env["rack.exception"] = $!
    false
  end
```

**Comment by Wardrop** [comment]
Does anything else use `env['rack.exception']`? It doesn't seem to be used in the Rack codebase at all. The closest I could find was env['rack.errors'] which `$stderr` is normally assigned to; it's just an error stream basically.

Could you give an example of how you'd use this feature? 

By the way, with your example, did you know you that the exception that caused your error filters to run is given to the block as an argument. You should rewrite your "hack" as:

```ruby
error do |e|
  env["rack.exception"] = e
  false
end
```

**Comment by CrowdHailer** [comment]
I am using bugsnag for error tracking that works off that. Obviously that in itself is not a reason to add it. However they do assume it in their middleware for rack [line 41](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/rack.rb) and I think it is present in sinatra.

**Comment by Wardrop** [comment]
I'll consider adding it in a future release; can't do any harm I suppose. In the mean time, use that code I posted as that's probably how I'd implement it internally anyway. I'll leave this issue open to remind me.

**Comment by CrowdHailer** [comment]
Well I like keeping it minimal. Also as the framework is pretty malliable by including modules I think what might be interesting is to put together some various 'addin packs' (hesitant to call them plugins when they are just ruby modules.)

e.g. html module

```rb
module HTMLPack
    def self.included(klass)
      klass.error do |e|
        env["rack.exception"] = e
        false
      end
    end

    def csrf_tag
      Rack::Csrf.csrf_tag(env)
    end

    # Return the anti-CSRF token
    def csrf_token
      Rack::Csrf.csrf_token(env)
    end

    # Return the field name which will be looked for in the requests.
    def csrf_field
      Rack::Csrf.csrf_field
    end

    def deny_access
      flash['error'] = 'Access denied'
      redirect '/'
    end

    def redirect(*args, **flashes)
      flashes.each { |k,v| flash[k] = v }
      super *args
    end
end

**Comment by CrowdHailer** [comment]
Airbrake also uses the same assumption of this being prescent

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack.rb

**Comment by Wardrop** [comment]
I think I'll add this to the next release of Scorched, which is likely not too far away.

**Comment by CrowdHailer** [comment]
Is there a good place to make suggestions for features. I was wondering if you might be interested in setting up a gitter channel, I have enjoyed using them on other projects

**Comment by Wardrop** [comment]
I would suggest just raising a Github issue and labelling it as an enhancement.
