### ISSUE TITLE
Flash messages not being set in after block

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#37]
I am currently trying to set a flash message in an after block 

```rb
after :status => 404 do
    flash['error'] = 'Page not found'
    redirect '/'
  end
```

The redirection works but changes to the flash are not being added. I have tested and an empty flash hash and session hash are both correctly available in the error block

**Comment by CrowdHailer** [comment]
My mistake. The flash is working fine but my automated testing is not picking up flashes generated in after blocks. I have the same code to test flashes set in routes as in after blocks using the following helper

```rb
def flash
    last_request.env['scorched.flash'][:flash]
  end
```

**Comment by Wardrop** [comment]
Why don't you test using the standard method of access, i.e. `flash[:some_key]` rather than testing part of the underlying implementation which may not reflect your assumptions.

**Comment by CrowdHailer** [comment]
I was trying to test outside the controller. Using minitest and rack/test. I wanted too just test the flash that was saved rather than viewing a new page and checking it was there.
