### ISSUE TITLE
 render  "test.erb"    return plain text 

### ISSUE THREAD

**Issue by tablecell** [Wardrop/Scorched#43]
```RUBY
  get '/tpl' do 

	render  "test.erb"

  end 
```
visit  http://localhost:9292/tpl

display   string  "test.erb"

**Comment by tmilker** [comment]
You want
```
    render :'test'
```
if you're trying to render a template.  You're just telling it to render a string.

**Comment by Wardrop** [comment]
Correct, as @tmilker said, if you give `render` a string, it'll treat that string itself as template and render it as if it were the contents of an ERB file. Using a symbol instead tells Scorched to look for a file with that name and to render that.

**Comment by tablecell** [comment]
`render  :test `  works .
thanks for your help

**Comment by tablecell** [comment]
```RUBY
require "scorched"

class App < Scorched::Controller
  get "/blog" do
    "root"
  end

  controller "/blog" do
    get "/user" do
      "user"
    end

    get "/article" do
      "article"
    end

    controller "/user" do
      get "/login" do
        "login"
      end
    end
    get "/phptogallery" do
      "image"
    end
  end
end
```
if  'controller '  should be  'map' or 'mount' is  more  readable ?

**Comment by tmilker** [comment]
I organize my apps like:

```ruby
class App < Scorched::Controller
  before do
      # app stuff before controllers like auth
  end
end

class BlogController < Scorched::Controller
  get '/user' do
    "user"
  end
end

App << {pattern: '/blog', priority: -99, target: BlogController}
```

Typically I don't use the bare Scorched::Controller though, I have my own ScorchedApp::Application and ScorchedApp::Controller.
