### ISSUE TITLE
media_type: 'application/json'  return  Content-Type "text/html;charset=utf-8"

### ISSUE THREAD

**Issue by tablecell** [Wardrop/Scorched#44]
```RUBY
    get '/:id'   ,media_type: 'application/json' do

    #  id=  captures[:id]
     Tasks[1].to_hash.to_json
 
    end
````

**Comment by Wardrop** [comment]
That's a condition. It determine what requests that endpoint/route handles. It doesn't change the response headers. 

Your example basically translates to: for any GET request to '/*' with the request header set to "Accept: application/json", do this.

**Comment by tmilker** [comment]
You have to manage your own return response Content-Types.  No magic here.
